CREATE DATABASE IF NOT EXISTS usman_portfolio;
USE usman_portfolio;

CREATE TABLE IF NOT EXISTS site_content (
  id INT PRIMARY KEY,
  content JSON NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_users (
  id VARCHAR(64) PRIMARY KEY,
  username VARCHAR(120) NOT NULL UNIQUE,
  email VARCHAR(190),
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'admin',
  last_login TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS media_files (
  id VARCHAR(64) PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  type VARCHAR(32) NOT NULL,
  size BIGINT NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  used_in JSON
);

CREATE TABLE IF NOT EXISTS version_history (
  id VARCHAR(64) PRIMARY KEY,
  snapshot_data JSON NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  label VARCHAR(190) NOT NULL,
  restored_at TIMESTAMP NULL
);
